name: rif
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_7
  - bioconductor-rsubread=1.34.0=r351h14c3975_0
  - bwidget=1.9.11=1
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.16.0=ha4e643d_1000
  - certifi=2019.3.9=py27_0
  - curl=7.64.1=hf8cf82a_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_7
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_7
  - glib=2.58.3=hf63aee3_1001
  - graphite2=1.3.13=hf484d3e_1000
  - gsl=2.4=h294904e_1006
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_7
  - harfbuzz=2.4.0=h37c48d4_0
  - icu=58.2=hf484d3e_1000
  - jpeg=9c=h14c3975_1001
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libcurl=7.64.1=hda55be3_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=10_openblas
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h9022e91_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - macs2=2.1.2=py27r351h14c3975_1
  - make=4.2.1=h14c3975_2004
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.16.4=py27h95a1406_0
  - openblas=0.3.6=h6e990d7_2
  - openssl=1.1.1b=h14c3975_1
  - pandoc=2.7.2=0
  - pango=1.40.14=h4ea9474_1004
  - pcre=8.41=hf484d3e_1003
  - pip=19.1=py27_0
  - pixman=0.34.0=h14c3975_1003
  - pthread-stubs=0.4=h14c3975_1001
  - python=2.7.15=h721da81_1008
  - r-askpass=1.1=r351h96ca727_0
  - r-assertthat=0.2.1=r351h6115d3f_0
  - r-backports=1.1.4=r351hcdcec82_0
  - r-base=3.5.1=h271c98b_1006
  - r-base64enc=0.1_3=r351h96ca727_1002
  - r-bh=1.69.0_1=r351h6115d3f_0
  - r-broom=0.5.2=r351h6115d3f_0
  - r-callr=3.2.0=r351h6115d3f_0
  - r-cellranger=1.1.0=r351h6115d3f_1001
  - r-cli=1.1.0=r351h6115d3f_0
  - r-clipr=0.6.0=r351h6115d3f_0
  - r-colorspace=1.4_1=r351hcdcec82_0
  - r-crayon=1.3.4=r351h6115d3f_1001
  - r-curl=3.3=r351h96ca727_0
  - r-dbi=1.0.0=r351h6115d3f_1001
  - r-dbplyr=1.4.0=r351h6115d3f_0
  - r-digest=0.6.19=r351h0357c0b_0
  - r-dplyr=0.8.1=r351h0357c0b_0
  - r-ellipsis=0.1.0=r351h96ca727_0
  - r-evaluate=0.14=r35h6115d3f_0
  - r-fansi=0.4.0=r351h96ca727_1000
  - r-forcats=0.4.0=r351h6115d3f_0
  - r-fs=1.3.1=r351h0357c0b_0
  - r-generics=0.0.2=r351h6115d3f_1001
  - r-getopt=1.20.3=r351_0
  - r-ggplot2=3.1.1=r351h6115d3f_0
  - r-glue=1.3.1=r351hcdcec82_0
  - r-gtable=0.3.0=r351h6115d3f_0
  - r-haven=2.1.0=r351h29659fb_0
  - r-highr=0.8=r351h6115d3f_0
  - r-hms=0.4.2=r351h6115d3f_1000
  - r-htmltools=0.3.6=r351hf484d3e_1002
  - r-httr=1.4.0=r351h6115d3f_1000
  - r-jsonlite=1.6=r351h96ca727_1000
  - r-knitr=1.23=r351h6115d3f_0
  - r-labeling=0.3=r351h6115d3f_1001
  - r-lattice=0.20_38=r351h96ca727_1000
  - r-lazyeval=0.2.2=r351hcdcec82_0
  - r-lubridate=1.7.4=r351h29659fb_1001
  - r-magrittr=1.5=r351h6115d3f_1001
  - r-markdown=0.9=r351h96ca727_1000
  - r-mass=7.3_51.4=r351hcdcec82_0
  - r-matrix=1.2_17=r351hcdcec82_0
  - r-mgcv=1.8_28=r351hcdcec82_0
  - r-mime=0.6=r351h96ca727_1000
  - r-modelr=0.1.4=r351h6115d3f_0
  - r-munsell=0.5.0=r351h6115d3f_1001
  - r-nlme=3.1_140=r351h9bbef5b_0
  - r-openssl=1.3=r351h9c8475f_0
  - r-pillar=1.4.1=h6115d3f_0
  - r-pkgconfig=2.0.2=r351h6115d3f_1001
  - r-plogr=0.2.0=r351h6115d3f_1001
  - r-plyr=1.8.4=r351h29659fb_1002
  - r-prettyunits=1.0.2=r351h6115d3f_1001
  - r-processx=3.3.1=r351hcdcec82_0
  - r-progress=1.2.2=r351h6115d3f_0
  - r-ps=1.3.0=r351h96ca727_1000
  - r-purrr=0.3.2=r351hcdcec82_0
  - r-r6=2.4.0=r351h6115d3f_0
  - r-rcolorbrewer=1.1_2=r351h6115d3f_1001
  - r-rcpp=1.0.1=r351h0357c0b_0
  - r-readr=1.3.1=r351h29659fb_1000
  - r-readxl=1.3.1=r351h0357c0b_0
  - r-rematch=1.0.1=r351h6115d3f_1001
  - r-reprex=0.3.0=r351h6115d3f_0
  - r-reshape2=1.4.3=r351h29659fb_1003
  - r-rlang=0.3.4=r351hcdcec82_0
  - r-rmarkdown=1.12=r351h6115d3f_0
  - r-rstudioapi=0.10=r351h6115d3f_0
  - r-rvest=0.3.4=r351h6115d3f_0
  - r-scales=1.0.0=r351h29659fb_1001
  - r-selectr=0.4_1=r351h6115d3f_1000
  - r-stringi=1.4.3=r351h0357c0b_0
  - r-stringr=1.4.0=r351h6115d3f_0
  - r-sys=3.2=r351hcdcec82_0
  - r-tibble=2.1.1=r351hcdcec82_0
  - r-tidyr=0.8.3=r351h0357c0b_0
  - r-tidyselect=0.2.5=r351h29659fb_1000
  - r-tidyverse=1.2.1=r351h6115d3f_1001
  - r-tinytex=0.13=r351h6115d3f_0
  - r-utf8=1.1.4=r351h96ca727_1000
  - r-vctrs=0.1.0=r351h96ca727_1000
  - r-viridislite=0.3.0=r351h6115d3f_1001
  - r-whisker=0.3_2=r351h6115d3f_1001
  - r-withr=2.1.2=r351h6115d3f_1000
  - r-xfun=0.7=r351h6115d3f_0
  - r-xml2=1.2.0=r351h29659fb_1002
  - r-yaml=2.2.0=r351h96ca727_1001
  - r-zeallot=0.1.0=r351h6115d3f_1000
  - readline=7.0=hf8c457e_1001
  - samtools=1.9=h8571acd_11
  - setuptools=41.0.1=py27_0
  - sqlite=3.28.0=h8b20d00_0
  - tk=8.6.9=h84994c4_1001
  - tktable=2.10=h14c3975_0
  - wheel=0.33.4=py27_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.3.3=1
prefix: /N/u/rpolicas/Carbonate/.conda/envs/rif

